// graphics
pub const RESOLUTION_WIDTH = 160;
pub const RESOLUTION_HEIGHT = 144;
pub const SCALING = 6;

pub const WINDOW_WIDTH = RESOLUTION_WIDTH * SCALING;
pub const WINDOW_HEIGHT = RESOLUTION_HEIGHT * SCALING;

pub const TILE_WIDTH = 8;
pub const RESOLUTION_TILE_WIDTH = RESOLUTION_WIDTH / TILE_WIDTH;

pub const BYTE_PER_LINE = 2;
pub const NUM_2BPP = RESOLUTION_TILE_WIDTH * BYTE_PER_LINE * RESOLUTION_HEIGHT;

// audio
pub const NUM_SAMPLES = 32;
