const std = @import("std");
const assert = std.debug.assert;

const MemMap = @import("mem_map.zig");
const MMU = @import("mmu.zig");

const Self = @This();

// TODO: Super unclear how samples generated by GB are pushed onto the soundbuffer in sfml?
pub fn step(_: *Self, _: *MMU, _: *[]i16) void {
}
