const std = @import("std");
const test_options = @import("test_options");

// unit tests
const UnitTestFile = struct {
    file: []const u8 = undefined,
    category: test_options.@"build.TestCategory" = .all,
    test_functions: []const []const u8 = undefined,
};

const unit_test_folder = "src/tests/";
const unit_tests: [5]UnitTestFile = .{
    //.{ .file = "apu", .category = .apu , .test_functions = &.{ "runApuChannelTests" } },
    //.{ .file = "apu_sampling", .category = .apu, .test_functions = &.{ "runApuSampingTests", "runApuOutputTest" } },
    .{ .file = "cart", .category = .cart , .test_functions = &.{ "runCartTests" } },
    .{ .file = "halt", .category = .cpu , .test_functions = &.{ "runHaltTests" } },
    .{ .file = "interrupt", .category = .cpu , .test_functions = &.{ "runInterruptTests" } },
    .{ .file = "memory", .category = .memory , .test_functions = &.{ "runDMATest", "runRequestTest" } },
    .{ .file = "mmio", .category = .mmio , .test_functions = &.{ "runDividerTests", "runInputTests", "runTimerTest" } },
    //.{ .file = "ppu", .category = .ppu , .test_functions = &.{ "runInterruptTests" } },
    //.{ .file = "singlestep_test", .category = .instruction , .test_functions = &.{ "runSingleStepTests" } },
};

// TODO: Use actual name for this later.
const output_file_path = "src/test2.zig";
const output_start = 
    \\/////////////////////////////////////////////////
    \\/// AUTO GENERATED FILE. DO NOT EDIT MANUALLY
    \\/// GENERATED BY 'zig build test'
    \\/////////////////////////////////////////////////
    \\
    \\const std = @import("std");
    \\const test_options = @import("test_options");
    \\const category = test_options.test_category;
    \\
    \\
;
const output_import = 
    \\const {0s}_test = @import("tests/{0s}.test.zig");
    \\
;
const output_test =
    \\test "{0s}_{1s}" {{
    \\    if (category != .all and category != .{0s}) {{
    \\        return error.SkipZigTest;
    \\    }}
    \\    try {2s}_test.{1s}();
    \\}}
    \\
    \\
;

pub fn main() !void {
    var timer: std.time.Timer = try .start();
    defer {
        const elapsed: f64 = @floatFromInt(timer.read());
        std.log.info("Tests generated in: {}ms", .{ elapsed / std.time.ns_per_ms });
    }

    var gpa: std.heap.GeneralPurposeAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc: std.mem.Allocator = gpa.allocator();

    var writer: std.io.Writer.Allocating = .init(alloc);
    defer writer.deinit();

    try writeUnitTest(&writer.writer);

    var result: std.ArrayList(u8) = writer.toArrayList();
    defer result.deinit(alloc);
    std.fs.cwd().writeFile(.{ .data = result.items, .sub_path = output_file_path }) catch unreachable;
}

fn writeUnitTest(writer: *std.io.Writer) !void {
    try writer.writeAll(output_start);
    for(unit_tests) |unit_test| {
        try writer.print(output_import, .{ unit_test.file });
        for(unit_test.test_functions) |unit_test_function| {
            try writer.print(output_test, .{ @tagName(unit_test.category), unit_test_function, unit_test.file });
        }
    }
}
