/////////////////////////////////////////////////
/// AUTO GENERATED FILE. DO NOT EDIT MANUALLY
/// GENERATED BY 'zig build test'
/////////////////////////////////////////////////

const std = @import("std");
const test_options = @import("test_options");
const category = test_options.test_category;

const cart_test = @import("tests/cart.test.zig");
test "cart_runCartTests" {
    if (category != .all and category != .cart) {
        return error.SkipZigTest;
    }
    try cart_test.runCartTests();
}

const halt_test = @import("tests/halt.test.zig");
test "cpu_runHaltTests" {
    if (category != .all and category != .cpu) {
        return error.SkipZigTest;
    }
    try halt_test.runHaltTests();
}

const interrupt_test = @import("tests/interrupt.test.zig");
test "cpu_runInterruptTests" {
    if (category != .all and category != .cpu) {
        return error.SkipZigTest;
    }
    try interrupt_test.runInterruptTests();
}

const memory_test = @import("tests/memory.test.zig");
test "memory_runDMATest" {
    if (category != .all and category != .memory) {
        return error.SkipZigTest;
    }
    try memory_test.runDMATest();
}

test "memory_runRequestTest" {
    if (category != .all and category != .memory) {
        return error.SkipZigTest;
    }
    try memory_test.runRequestTest();
}

const mmio_test = @import("tests/mmio.test.zig");
test "mmio_runDividerTests" {
    if (category != .all and category != .mmio) {
        return error.SkipZigTest;
    }
    try mmio_test.runDividerTests();
}

test "mmio_runInputTests" {
    if (category != .all and category != .mmio) {
        return error.SkipZigTest;
    }
    try mmio_test.runInputTests();
}

test "mmio_runTimerTest" {
    if (category != .all and category != .mmio) {
        return error.SkipZigTest;
    }
    try mmio_test.runTimerTest();
}

